### ISSUE TITLE
[Tripal V2] : Issues in biomaterial loader

### ISSUE THREAD

**Issue by mboudet** [tripal/tripal_analysis_expression#248]
Hello,
There are three 'issues' in the V2 biomaterial loader

1.  In V3, the dbxref_id of the biomaterial is set to Null at all time[(here)](https://github.com/tripal/tripal_analysis_expression/blob/master/tripal_biomaterial/includes/TripalImporter/tripal_biomaterial_loader_v3.inc#L483). In V2, it is set to the 'biosample' dbxref if existing [here](https://github.com/tripal/tripal_analysis_expression/blob/v7.x-2.x/includes)/tripal_biomaterial_loader.inc#L617). I suppose the correct way is the V3? (Is the biomaterial dbxref_id ever set?)

2. Same as #247, the XML file ignore the BioProject accession

3. The flat file ignore the BioSample Accession anyway, because it is in the $acc_headers variable [here](https://github.com/tripal/tripal_analysis_expression/blob/v7.x-2.x/includes/tripal_biomaterial_loader.inc#L318), and we check the $biomaterial_headers variable [here](https://github.com/tripal/tripal_analysis_expression/blob/v7.x-2.x/includes/tripal_biomaterial_loader.inc#L352)

**Comment by bradfordcondon** [comment]
>In V3, the dbxref_id of the biomaterial is set to Null at all time(here). In V2, it is set to the 'biosample' dbxref if existing here/tripal_biomaterial_loader.inc#L617). I suppose the correct way is the V3? (Is the biomaterial dbxref_id ever set?)


The original author of this module misunderstood this.  The biomaterial.dbxref_id is for the **INTERNAL** accession.  They previously used it for one of the ncbi accessions which is incorrect and caused problems with the tripal 3 version of the display.
It would be feasible to specify a way to find/build an internal dbxref but given as we don't support it i'd ask that such functionality be contributed.

>Same as #247, the XML file ignore the BioProject accession

I'll fix this when i get a minute. 

>The flat file ignore the BioSample Accession anyway, because it is in the $acc_headers variable here, and we check the $biomaterial_headers variable here

I wonder if this is related to your first issue?  t was previously loaded as the  PRIMARY, INTERNAL ACCESSION when it should not have been?  And now we dont use it instead of adding it as an additional external accession as we should?

Honestly my support for the flatfile is limited.  This is a monster of a module to maintain and i prioritized fixing and updating the XML importer over the flat (they are implemented totally separately unfortunately).
Are  you using flatfiles, XML, or both?  Trying to figure out which to use?  If you can just use XML that would be best for me :D

**Comment by mboudet** [comment]
> The original author of this module misunderstood this. The biomaterial.dbxref_id is for the **INTERNAL** accession. They previously used it for one of the ncbi accessions which is incorrect and caused problems with the tripal 3 version of the display.

Should be easy to fix, I'll make a pull request for this (at least for setting the value to null)


> I wonder if this is related to your first issue? t was previously loaded as the PRIMARY, INTERNAL ACCESSION when it should not have been? And now we dont use it instead of adding it as an additional external accession as we should?

It might be!

> Honestly my support for the flatfile is limited. This is a monster of a module to maintain and i prioritized fixing and updating the XML importer over the flat (they are implemented totally separately unfortunately).

This part should be fixable without too much work, I will work on it.

> Are you using flatfiles, XML, or both? Trying to figure out which to use? If you can just use XML that would be best for me :D

Well, to be honest I'm working on a python API / cli for working with either tripal (python-tripal) or chado (python-chado) directly, so "I" don't actually use anything. For now, I'm just keeping the existing features.

**Comment by mboudet** [comment]
Fixed (partial) by #249.
I'm closing it because the remaining issue is linked to #247 , and would be fixed at the same time.
