### ISSUE TITLE
[Tripal V2] Heatmap script blocked by adblocker

### ISSUE THREAD

**Issue by mboudet** [tripal/tripal_analysis_expression#253]
The heatmap.js file in /theme/js/heatmap.js is being blocked by some adblocker filter.
(regex on /heatmap.*? for whatever reason). 

This filter is set by default in ublock (EasyPrivacy filter list), so it might impact some people.

It would probably be fixed by changing the name of the file, or by setting a warning about it in the README.

**Comment by almasaeed2010** [comment]
That's interesting. I am not sure if this is something we need to worry about though. It's kinda impossible for us to test every adblocker just to verify the name of the file is accepted. Since has been discovered, we should probably change the name to something else in both the t2 and t3 versions.

Thanks!

**Comment by mboudet** [comment]
Agreed about not worrying about every adblocker. 
In this case, the filter is bundled with every new install of at least two fairly popular adblockers, so it might cause issues for more users. 

(I'm questioning the need for a /heatmap/ filter. It looks like it has been causing problems since 2014..)

**Comment by noahcaldwell7** [comment]
No updates in over a year, closing issue.
