### ISSUE TITLE
Enable user to download expression values

### ISSUE THREAD

**Issue by mestato** [tripal/tripal_analysis_expression#45]
Currently its difficult for a user to download gene expression values to perform their own visualization. We need a button or link to download the raw data as a CSV. The usual matrix format would be best - genes as rows, biomaterials as columns, normalized values filling out the middle. This would be great in 3 places:
1. the analysis record page - download all values
2. the feature page, expression tab - download values for this feature
3. the expression tool - download the values for the features entered into the search box

**Comment by bradfordcondon** [comment]
Part of me wants to implement this via collections.  But it's super challenging to define because collections wants a group of entities, and these expression values are stored via the chado_mage schema.  If they could somehow be a field for a feature, that would work.  But they would need to get both all biomaterials with expression type analyses, as well as the corresponding elementresult.signal.

So yeah the other part of me thinks we won't offer this via collections.

**Comment by bradfordcondon** [comment]
Implemented: #106 #109
