### ISSUE TITLE
Load and Display statistics especially p values

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal_analysis_expression#48]
The goal is easy- associate p values with a given expression value for a given gene.

The implementation is hard.  

What does that p value mean- that it was significantly upregulated?  downregulated?  Compared to what?
How does it get stored?  If its just a p value, then it can be stored similar to units in `quantificationprop`.  If its more than that (ie details of the statistical test... and it probably should be) would this additional info also go in `quantificationprop` or somewhere else?

**Comment by bradfordcondon** [comment]
i would actually be happy to work on this a bit as a separate module. If I had some sample input data.  I'm moving this to a "HWG" issue because i think its too big for the scope of this module.

**Comment by mestato** [comment]
Reopening because I've decided this could go in this module and I can't find the issue in HWG. Needs planning though.

**Comment by mestato** [comment]
New plan:
- store ontology terms that describes the statically significant expression change found in an analysis. EG "upregulated under heat stress" could be broken down in the term "upregulated" (SIO?) and "heat stress" (GO). maybe also an "expression" term?
- use feature_cvterm table
- use feature_cvtermprop to store the analysis id

Display the cv terms specifically derived from the analysis on the expression pane.

**Comment by mestato** [comment]
Suggest starting with green ash paper:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5009568/

See Additional file 4 for differentially expressed gene lists.

**Comment by bradfordcondon** [comment]
>store ontology terms that describes the statically significant expression change found in an analysis. EG "upregulated under heat stress" could be broken down in the term "upregulated" (SIO?) and "heat stress" (GO). maybe also an "expression" term?


@mestato interesting idea.  How can we do this when we cant have compound terms?  Would you associate all 3 terms (heat stress, upregulated, expression) with the feature via feature_cvterm?  And each feature_cvterm is also tagged with the feature_cvtermprop?

But what if a feature was upregulated under heat stress in biosample A, but downregulated under heat stress in biosample B?

**Comment by mestato** [comment]
> How can we do this when we cant have compound terms?
We can have as many terms associated with a feature as needed. It would be nice to group them, though, which maybe we could do with rank. For example a gene could be up regulated with drought but down regulated under heat, so we'd need a way to know which terms go together. If that does work we'll have to figure something else out.

> Would you associate all 3 terms (heat stress, upregulated, expression) with the feature via feature_cvterm? 
Yes

> And each feature_cvterm is also tagged with the feature_cvtermprop?
Yes, the analysis_id and the p value will be associated with all.

> But what if a feature was upregulated under heat stress in biosample A, but downregulated under heat stress in biosample B?
If they are different analyses, that isn't a problem. We'll just know the "conflicting" information came from different sources. For a single experiment, with multiple heat stress biosamples as you suggest, we already store the individual gene level in each biosample. However, an appropriate DE statistical analysis should use the biological replicates as part of the stats and look for significance, which is what we are storing with the cv terms.

**Comment by mestato** [comment]
I finally found the part of TAIR i remembered that inspired this (when abdullah and I looked at it I got totally distracted by the awesome eFP browser stuff!). Basically, we need to rethink this functionality just a bit, as a larger system of evidence-based annotation. This screenshot is an "annotation detail" page from TAIR, which has all the annotations for a single locus. It includes the ontology term and the evidence code (Including "inferred from expression pattern") and the publication. Nice!

![screen shot 2018-12-08 at 7 09 08 pm](https://user-images.githubusercontent.com/508122/49692003-3ebd0b00-fb1d-11e8-9fa7-77a2d253ea6f.png)

Full page at https://www.arabidopsis.org/servlets/Search?action=search&type=annotation&tair_object_id=2025391&locus_name=AT1G01620

I guess they decided not to mess with storing actual p-values, which makes sense if you are accepting many evidence types that might have varying statistical tests. I still think we could probably incorporate this data.

This is from the main page of the locus, which I like less, because its really easy to miss the "Annotation detail" link and then not know how this data was generated. But it is a pretty sweet overview of all knowledge about a locus organized by CV.

![screen shot 2018-12-08 at 7 08 34 pm](https://user-images.githubusercontent.com/508122/49692028-b68b3580-fb1d-11e8-82b6-a2aa64eb2eaa.png)

Full page: https://www.arabidopsis.org/servlets/TairObject?id=29127&type=locus

**Comment by mestato** [comment]
Evidence code ontology: https://www.arabidopsis.org/servlets/TairObject?type=definitions&id=500101506

**Comment by mestato** [comment]
Note to not forget later: we need to add an "inferred by electronic evidence" evidence code to IPS-based GO term associations (maybe PR on tripal IPS module?)

**Comment by mestato** [comment]
Example:
Fraxinus_pennsylvanica_120313_comp45571_co0_seq1 appears on tab labeled "Heat Down"

feature_cvterm: GO:0009408 response to heat (rank 1)
feature_cvterm: up-regulated (need to work on finding term, see go_annotation_extension_relations.obo at http://wiki.geneontology.org/index.php/Relationships_between_annotation_objects_and_ontology_terms) (rank 1)
or use feature_cvtermprop to store this as a relationship (since there's no feature_cvterm_relationship)

How to know which is which? Use a comma separated list?

Moving on to evidence...
(Would be nice to have a feature_cvterm_analysis table but we dont' so use a prop)
feature_cvtermprop: analysis value, use analysis term as type
feature_cvtermprop: padj value, use some ontology term for padj (need to look up)

Yep still messy. Could we get evidence and relationship fields added to feature_cvterm table???

Something to talk about at PAG.

**Comment by mestato** [comment]
Perfect world feature_cvterm table fields:

feature_cvterm_id 
feature_id
cvterm_id 
pub_id
is_not 
rank
evidence_code_term (a cvterm id for evidence code) NEW
analysis_id NEW

Plus a new feature_cvterm_relationship table with these fields:

feature_cvterm_relationship_id
feature_cvterm_id
type_id
value
rank

Needs more thought.

**Comment by jwest60** [comment]
Few questions:
- Are we creating a new module for this?
- Should we convert each sheet of the spreadsheet to a csv or is there a better way?
- Do I need to create an OBO for the terms (`upregulated`, `heat`, etc.)?
- Do we need a data loader?

**Comment by jwest60** [comment]
[i created an importer](https://github.com/statonlab/tripal_analysis_expression/tree/p-values) that takes in a csv/tsv with two columns: one for feature names, and the other for p-values

this importer then loads the data into the database [as outlined by abdullah above](https://github.com/tripal/tripal_analysis_expression/issues/48#issuecomment-446672344)

i loaded in a file called `contig_oligo.csv` (two random cvterms that i knew i had in my db, realistically this would be called something like heat_down.csv or something) that looked something like this:
```
FRAEX38873_v2_000000010.1,1
FRAEX38873_v2_000000010.2,5
FRAEX38873_v2_000000020.1,8
FRAEX38873_v2_000000030.1,13
FRAEX38873_v2_000000040.1,12
FRAEX38873_v2_000000050.1,14
...
```

the file follows the aforementioned two column format, with feature names that i already had in my database

once loaded, the result gets stored in the database like this:

- feature_cvterm
![image](https://user-images.githubusercontent.com/32902460/53113398-8265c500-350f-11e9-9c7f-30e548e3c876.png)

the second column matches to the id of the feature (e.g. FRAEX38873_v2_000000010.1) and the third column is the cvterm_id for the first word of the filename (which is a cvterm, e.g. heat), which in this case is the cvterm_id for contig

- feature_cvtermprop
![image](https://user-images.githubusercontent.com/32902460/53117292-906c1380-3518-11e9-9b48-bea456cba7e2.png)


the second column matches to the id of the feature_cvterm, and three records are added for each feature_cvterm

- the first record contains the id (417) of the second word in the filename (also a cvterm, e.g. down), which in this case is oligo. this gets added in a new cvalue column coming to chado (but since it doesnt exist yet it gets added in module update_7300). the type_id is another cvterm that relates these two terms to one another (e.g. "involved in regulation") but in this case its just a hard-coded placeholder cvterm id (343)

- the second record contains the pvalue and the cvterm_id for p-value (again, another hard-coded placeholder, 344)

- the third record contains the analysis_id and the cvterm_id for analysis

theres a lot of hard coded values but it should be easy enough to swap them out with the real cvterm ids once i know what they are

**Comment by jwest60** [comment]
i created a field that adds a table to features listing the keyword (e.g. heat), the evidence code, the p-value, and the name of the analysis

![image](https://user-images.githubusercontent.com/32902460/53659400-78d40f80-3c29-11e9-9625-a7bb31e0ff23.png)

suggestions for other columns to add?

**Comment by almasaeed2010** [comment]
This looks great to me @jwest60.

I @bradfordcondon and @mestato should take a look at this. 

Also, the next step would be to choose the actual terms to describe each of those fields. Maybe we can ask them for help with that as well.

**Comment by jwest60** [comment]
importer can now update entries and can now insert entries in a more intelligent way (no more errors when you try to upload a file containing the same keyword and feature id)

theres also an evidence code field on the form so the user can choose "up-regulated", "down-regulated", or "related to".

as abdullah said above, it would be a good idea to start choosing actual terms for the fields, like the cvterms for the evidence code and pvalue

**Comment by jwest60** [comment]
pvalue loader no longer parses cvterms from the file name but gets them via text fields on the form 

![image](https://user-images.githubusercontent.com/32902460/55256754-3c99cc00-5234-11e9-86a7-32884d65360b.png)

these will autocomplete to the name of a cvterm in a cv in the database

more detailed descriptions will be added later

**Comment by jwest60** [comment]
since evidence code is no longer constant (up-regulated, down-regulated, related to), there doesnt seem to be any reliable way to grab the entry containing the evidence code, as all fields (type_id, cvalue_id, value) are all variable. this is the reason the table is crashing, since there's no way to retrieve the evidence code to display in the table

> Casting to make sure pvalues are handled correct no matter what numerical format

i just tested this by changing one of the pvalues to `3.70E-74`, and the data seems to get stored in the database correctly

![image](https://user-images.githubusercontent.com/32902460/55499610-6a0bbe80-5614-11e9-9917-dd0e1bfa98cc.png)

in this implementation, whatever is in the file will get represented exactly in the database. not sure if this is the functionality that we want though, for example in the case we were to want to represent `3.70E-74` in standard notation instead

**Comment by jwest60** [comment]
table is fixed and evidence code is now represented consistently in the db

![image](https://user-images.githubusercontent.com/32902460/55505059-3f276780-5620-11e9-9e08-9827ab42f719.png)

**Comment by mestato** [comment]
Request for relevant ontology terms for green ash data testing:
-  GO:0010193 response to ozone
-  GO:0009408 response to heat
-  GO:0009414 response to water deprivation
-  GO:0009409 response to cold
-  GO:0009611 response to wounding
-  GO:0009625 response to insect (might be labeled "EAB" for emerald ash borer)

**Comment by jwest60** [comment]
after performing some functional testing, i cant see a way that a user could reasonably break the loader.

the only issue i've noticed is that if a user provides a string in the second column instead of a pvalue, this gets inserted into the database as a 0.

**Comment by jwest60** [comment]
added some documentation on using the pvalue loader to the readme

**Comment by mestato** [comment]
File for testing with green ash: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5009568/bin/12864_2016_3052_MOESM4_ESM.xlsx

**Comment by jwest60** [comment]
all test cvterms have been removed and replaced with real cvterms

green ash cold up has been successfully uploaded and displays the pvalue [on dev](https://hardwoods.ag.utk.edu/bio_data/1396012?tripal_pane=group_pvalue)

there might be some formatting work to do but it's functioning. i can do more of the green ash file if needed (e.g. heat up, heat down, cold down)

**Comment by jwest60** [comment]
pvalue table now provides a link to the analysis

![image](https://user-images.githubusercontent.com/32902460/64030204-1c887480-cb14-11e9-8275-0ac4a5e35a32.png)

**Comment by jwest60** [comment]
#308 

the loader and field have now been merged into master and the documentation has been updated to reflect the changes
