### ISSUE TITLE
Expression heatmap does not accept features seperated by newline

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal_analysis_expression#73]
Values must be comma seperated ie
```FRAEX38873_v2_000001940.1,
FRAEX38873_v2_000001950.1,
FRAEX38873_v2_000001960.1,
FRAEX38873_v2_000001970.1,
FRAEX38873_v2_000001980.1,
FRAEX38873_v2_000002030.1,
FRAEX38873_v2_000001990.1,
FRAEX38873_v2_000002000.1,
FRAEX38873_v2_000002010.1,
FRAEX38873_v2_000002020.1,
FRAEX38873_v2_000001750.1,
FRAEX38873_v2_000001760.1
```

This is fine except the instructions state:

>Feature unique names need to be separated by comma, spaces, tabs or newlines.

Formats that work: 

* Comma seperated works

Formats that don't:
* TSV
* Newline
* Spaces

**Comment by almasaeed2010** [comment]
I don't think we should accept anything other than newlines and commas. You can't do tabs in a `textarea` and features are allowed to have spaces in the name so we can't do that either. And since adding allowing more than one type means we have to make sure that commas are removed when new lines are present and vice versa, it makes this a little harder than it seems to implement. So let's pick one and stick to it. My suggestion would be to keep the comma and update instructions accordingly.

**Comment by bradfordcondon** [comment]
im 100% on side of just changing instructions.

**Comment by almasaeed2010** [comment]
updated instructions.

Thanks!
